version: 2
builds:
- id: mcp-gateway-windows
  main: ./cmd/mcp-gateway
  binary: mcp-gateway
  ldflags:
    - -s -w
    - -X github.com/openziti/mcp-gateway/build.Version={{.Tag}}
    - -X github.com/openziti/mcp-gateway/build.Hash={{.ShortCommit}}
    - -X github.com/openziti/mcp-gateway/build.Date={{.Date}}
    - -X github.com/openziti/mcp-gateway/build.BuiltBy=goreleaser
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64

- id: mcp-bridge-windows
  main: ./cmd/mcp-bridge
  binary: mcp-bridge
  ldflags:
    - -s -w
    - -X github.com/openziti/mcp-gateway/build.Version={{.Tag}}
    - -X github.com/openziti/mcp-gateway/build.Hash={{.ShortCommit}}
    - -X github.com/openziti/mcp-gateway/build.Date={{.Date}}
    - -X github.com/openziti/mcp-gateway/build.BuiltBy=goreleaser
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64

- id: mcp-tools-windows
  main: ./cmd/mcp-tools
  binary: mcp-tools
  ldflags:
    - -s -w
    - -X github.com/openziti/mcp-gateway/build.Version={{.Tag}}
    - -X github.com/openziti/mcp-gateway/build.Hash={{.ShortCommit}}
    - -X github.com/openziti/mcp-gateway/build.Date={{.Date}}
    - -X github.com/openziti/mcp-gateway/build.BuiltBy=goreleaser
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64
